library globals;

import 'package:flutter/material.dart';

var bytes;
late String filepath;
late String updated;
late String? batch;
List<String> satRoutine = [];
List<String> sunRoutine = [];
List<String> monRoutine = [];
List<String> tueRoutine = [];
List<String> wedRoutine = [];
List<Widget> satRoutineWidgets = [];
List<Widget> sunRoutineWidgets = [];
List<Widget> monRoutineWidgets = [];
List<Widget> tueRoutineWidgets = [];
List<Widget> wedRoutineWidgets = [];
List<String> satRoutineEmpty = [];
List<String> sunRoutineEmpty = [];
List<String> monRoutineEmpty = [];
List<String> tueRoutineEmpty = [];
List<String> wedRoutineEmpty = [];
List<Widget> satRoutineWidgetsEmpty = [];
List<Widget> sunRoutineWidgetsEmpty = [];
List<Widget> monRoutineWidgetsEmpty = [];
List<Widget> tueRoutineWidgetsEmpty = [];
List<Widget> wedRoutineWidgetsEmpty = [];
var section;
var retake;
Color color = const Color.fromARGB(255, 28, 27, 31);
var courseNameJson = {};
var teacherNameJson = {};
